import type { ProcessedRecord, BoundingBox } from '@/types';

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generates an Oasis Montaj Geosoft XYZ file (.xyz) with standard channel headers.
 */
export function exportToOasisMontajXYZ(records: ProcessedRecord[], filename = 'topex_oasis_montaj.xyz'): void {
  const lines: string[] = [
    '/ Oasis Montaj Geosoft XYZ Data File',
    '/ Generated by TOPEX Interactive Downloader (v2.0)',
    `/ Date: ${new Date().toISOString()}`,
    '/ Coordinate System: WGS 84 (EPSG:4326)',
    '/ Channels: Longitude Latitude Topography_m FreeAir_mGal Bouguer_mGal SlabCorrection_mGal',
    '/',
    '/LINE 0',
    '/ X              Y              Topo_m         FAA_mGal       Bouguer_mGal   Slab_mGal',
  ];

  for (let i = 0; i < records.length; i++) {
    const r = records[i];
    const lon = r.longitude.toFixed(6).padStart(14, ' ');
    const lat = r.latitude.toFixed(6).padStart(14, ' ');
    const topo = (r.elevation !== undefined ? r.elevation.toFixed(2) : '*').padStart(14, ' ');
    const faa = (r.gravity !== undefined ? r.gravity.toFixed(3) : '*').padStart(14, ' ');
    const bg = (r.bouguer !== undefined ? r.bouguer.toFixed(3) : '*').padStart(14, ' ');
    const slab = (r.slabCorrection !== undefined ? r.slabCorrection.toFixed(3) : '*').padStart(14, ' ');

    lines.push(`${lon} ${lat} ${topo} ${faa} ${bg} ${slab}`);
  }

  downloadBlob(lines.join('\r\n'), filename, 'text/plain;charset=utf-8');
}

/**
 * Generates a Geosoft Grid eXchange Format (.gxf) ASCII raster file for Oasis Montaj / GM-SYS.
 */
export function exportToGeosoftGXF(
  records: ProcessedRecord[],
  bounds: BoundingBox,
  variable: 'bouguer' | 'freeAir' | 'topography' = 'bouguer',
  filename = 'topex_gravity_grid.gxf'
): void {
  // Sort records into a 2D matrix (latitude descending, longitude ascending)
  const lats = Array.from(new Set(records.map((r) => r.latitude))).sort((a, b) => b - a);
  const lons = Array.from(new Set(records.map((r) => r.longitude))).sort((a, b) => a - b);

  const nrows = lats.length;
  const ncols = lons.length;

  const dy = nrows > 1 ? Math.abs((bounds.north - bounds.south) / (nrows - 1)) : 0.016667;
  const dx = ncols > 1 ? Math.abs((bounds.east - bounds.west) / (ncols - 1)) : 0.016667;

  // Build grid lookup map
  const gridMap = new Map<string, number>();
  for (let i = 0; i < records.length; i++) {
    const r = records[i];
    const key = `${r.latitude.toFixed(4)}_${r.longitude.toFixed(4)}`;
    const val =
      variable === 'bouguer'
        ? r.bouguer ?? -999999
        : variable === 'freeAir'
        ? r.gravity ?? -999999
        : r.elevation ?? -999999;
    gridMap.set(key, val);
  }

  const varName =
    variable === 'bouguer'
      ? 'Complete Bouguer Gravity Anomaly (mGal)'
      : variable === 'freeAir'
      ? 'Free Air Gravity Anomaly (mGal)'
      : 'Topography / Bathymetry (m)';

  const lines: string[] = [
    '#TITLE',
    `TOPEX ${varName}`,
    '#POINTS',
    `${ncols}`,
    '#ROWS',
    `${nrows}`,
    '#PTSEP',
    `${dx.toFixed(6)}`,
    '#ROWSEP',
    `${dy.toFixed(6)}`,
    '#XORIGIN',
    `${bounds.west.toFixed(6)}`,
    '#YORIGIN',
    `${bounds.south.toFixed(6)}`,
    '#ROTATION',
    '0.0',
    '#SENSE',
    '1',
    '#DUMMY',
    '-999999',
    '#GRID',
  ];

  // Write row by row from north to south
  for (let r = 0; r < nrows; r++) {
    const rowVals: string[] = [];
    const lat = lats[r];
    for (let c = 0; c < ncols; c++) {
      const lon = lons[c];
      const key = `${lat.toFixed(4)}_${lon.toFixed(4)}`;
      const val = gridMap.get(key) ?? -999999;
      rowVals.push(val.toFixed(2));
    }
    lines.push(rowVals.join(' '));
  }

  downloadBlob(lines.join('\r\n'), filename, 'text/plain;charset=utf-8');
}
